version: '3.9'
name: steamflow-frontend

services:
  frontend:
    build: .
    image: abhi2425/streamflow
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - 3000:3000
networks:
  frontend: {}